University_system/force-app/main/default/objects/Course_Student__c/Course_Student__c.object-meta.xml
<CustomObject>
    <label>Course_Student</label>
    <nameField>
        <label>Course_Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course_Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/classes/StudentController.cls
public with sharing class StudentController {
    public studentController() {

    }
    @AuraEnabled
    public static List<Student__c> searchStudent(String studentName){
        try {
            return UniversityDAO.searchStudent(studentName);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static List<Course_Student__c> getCourcesOfStudent(Id studentId){
        try {
            return UniversityDAO.getCourcesOfStudent(studentId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}