University_system/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>40</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

University_system/force-app/main/default/objects/Course__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>40</relationshipLabel>
    <relationshipName>X40</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/Course_Student__c.object-meta.xml
<CustomObject>
    <label>Course_Student</label>
    <nameField>
        <label>Course_Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course_Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course_Student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Flow__c/fields/Number_of_students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_students__c</fullName>
    <label>Number of students</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Format_of_education__c.field-meta.xml
<CustomField>
    <fullName>Format_of_education__c</fullName>
    <label>Format of education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full time</fullName>
                <default>true</default>
                <label>Full time</label>
            </value>
            <value>
                <fullName>Distance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Grand__c.field-meta.xml
<CustomField>
    <fullName>Grand__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do you student study for money or by grand</description>
    <label>Grand</label>
    <type>Checkbox</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Teacher__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/classes/BindTeacherToFlowCoursesTest.cls
@isTest
public with sharing class BindTeacherToFlowCoursesTest {
    @TestSetup
    static void makeData(){
        Specialty__c testSpecialty = new Specialty__c(Name='Test Specialty',
                                                      Code__c = 'Test');
        insert(testSpecialty);                                              
        Course__c testCourse = new Course__c(Name = 'Test Course',
                                             Hours__c = 90,
                                             Specialty__c = testSpecialty.Id,
                                             Code__c = 'Test');
        Flow__c testFlow = new Flow__c(Name = 'test',
                                       Start_Date__c = Date.newInstance(2000, 10, 10),
                                       Format_of_education__c = 'FullTime',
                                       Number_of_students__c = 0,
                                       Specialty__c = testSpecialty.Id);
        insert(testFlow);
        
        Teacher__c testTeacher = new Teacher__c(Full_Name__c = 'Test Teacher', 
                                                Email__c = 'teacher@test.te',
                                                Contact_phone_number__c = '999951587');
        List<Student__c> testStudents = new List<Student__c>();
        for(StudentDTO studDTO : TestDataFactory.generateStudentDTO(20)){
            testStudents.add(new Student__c(Full_Name__c = studDTO.fullName,
                                            Email__c = studDTO.email,
                                            Contact_phone_number__c = studDTO.phoneNumber,
                                            Grand__c = studDTO.grand,
                                            Flow__c = testFlow.Id,
                                            Specialty__c = testFlow.Specialty__c));
        }
        
        //insert(testSpecialty);
        //insert(testFlow);
        insert(testCourse);
        insert(testTeacher);
        insert(testStudents);
    }
    @isTest
    static void BindTeacherToFlowCourses(){
        String[] error = new String[]{
            'Uptade Course_Student__c object is not successful',
            'Expected and actual teacherIds are different'};
        Id teacherId = [SELECT Id FROM Teacher__c LIMIT 1].Id;
        Id flowId = [SELECT Id FROM Flow__c LIMIT 1].Id;
        Id courseId = [SELECT Id FROM Course__c LIMIT 1].Id;
        Test.startTest();
        List<Database.SaveResult> results = UniversityServices.bindTeacherToFlowCourses(teacherId, flowId, courseId);
        Test.stopTest();
        Set<Id> courseStudentsId = new Set<Id>();
        for(Database.SaveResult result : results){
            system.assert(result.isSuccess(),error[0]);
            courseStudentsId.add(result.getId());
        }
        List<Course_Student__c> testCourseStudents = [SELECT Id, Teacher__c
                                                      FROM Course_Student__c 
                                                      WHERE Id in:courseStudentsId];
        for(Course_Student__c testCourseStudent : testCourseStudents){
            system.assertEquals(teacherId, testCourseStudent.Teacher__c, error[1]);
        }
    }
}