University_system/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>40</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

University_system/force-app/main/default/objects/Course__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>40</relationshipLabel>
    <relationshipName>X40</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Grand__c.field-meta.xml
<CustomField>
    <fullName>Grand__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do you student study for money or by grand</description>
    <label>Grand</label>
    <type>Checkbox</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/classes/TestDataFactory.cls
public abstract class TestDataFactory {

    public static List<StudentDTO> generateStudentDTO(Integer quantity){
        List<StudentDTO> students = new List<StudentDTO>();
        for(Integer i = 0; i<quantity; i++){
            students.add(new StudentDTO(
                'Test'+ i,
                false,
                'test' + i+'@test.com',
                '12345678'+i
            ));
        }
        return students;
    }
    public static List<Student__c> generateStudents(Id flowId, Id specialtyId, Integer num){
        List<Student__c> students = new List<Student__c>();
        for(Integer i = 0; i<num; i++){
            students.add(new Student__c(
                Full_Name__c = 'Test'+i,
                Flow__c = flowId,
                Specialty__c = specialtyId,
                Contact_Phone_Number__c = '68686868',
                Grand__c = false,
                Email__c = i+'test@email.te'

            ));
        }
        return students;
    }
    public static List<Course__c> generateCourse(Id specialtyId, Integer num){
        List<Course__c> courses = new List<Course__c>();
        for(Integer i = 0 ; i<num; i++){
            courses.add(new Course__c(
                Name='Test'+i,
                Specialty__c = specialtyId,
                Code__c = 'TE',
                Hours__c = 90
            ));
        }
        return courses;
    }
}