University_system/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>40</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

University_system/force-app/main/default/objects/Course__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>40</relationshipLabel>
    <relationshipName>X40</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Teacher__c/Course_Teacher__c.object-meta.xml
<CustomObject>
    <label>Course_Teacher</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course_Teacher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course_Teacher__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course_Teacher</relationshipLabel>
    <relationshipName>Course_Teacher</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Teacher__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Course_Teacher</relationshipLabel>
    <relationshipName>Course_Teacher</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Teacher__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/classes/BindTeacherToCourseTest.cls
@isTest
public with sharing class BindTeacherToCourseTest {
    /*
    public static List<Database.UpsertResult> bindTeacherToCourse(Id teacherId, Set<Id> coursesId){
        List<Course_Teacher__c> courseTeachers = new List<Course_Teacher__c>();
        for(Id courseId : coursesId){
            courseTeachers.add(new Course_Teacher__c(Course__c = courseId, Teacher__c = teacherId));
        }
        return Database.upsert(courseTeachers);
    }   
     */
    @TestSetup
    static void makeData(){
        Specialty__c testSpecialty = new Specialty__c(Name='Test Specialty',
                                                      Code__c='Test'); 
        insert testSpecialty;
        insert(new Teacher__c(Full_Name__c='Test Teacher',
                              Contact_phone_number__c='959494949',
                              Email__c ='test@tea.re'));
        List<Course__c> testCourses = new List<Course__c>();
        for(Integer i = 0; i<200;i++){
            testCourses.add(new Course__c(Name = 'Test'+i,
                                          Code__c = 'Code'+i,
                                          Specialty__c = testSpecialty.Id,
                                          Hours__c = 90));
        }
        insert(testCourses);
    }
    @isTest 
    static void bindTeacherToOneCourse(){
        String[] error = new String[]{
            'Upsert Course_Teacher error',
            'Course_Teacher`s TeacherId isn`t right'
        };

        Id teacherId = [SELECT Id FROM Teacher__c LIMIT 1].Id;
        Id courseId = [SELECT Id FROM Course__c LIMIT 1].Id;
        Test.startTest();
        Database.UpsertResult testResult = UniversityServices.bindTeacherToCourse(teacherId, new Set<Id>{courseId})[0];
        Test.stopTest();
        system.assert(testResult.isSuccess(),error[0]);
        Course_Teacher__c testCourseTeacher =
           [SELECT Teacher__c 
            FROM Course_Teacher__c 
            WHERE Id=:testResult.getId() 
            LIMIT 1];
        system.assertEquals(teacherId,testCourseTeacher.Teacher__c, error[1]);

    }
    @isTest
    static void bindTeacherToManyCourses(){
        String[] error = new String[]{
            'Upsert Course_Teacher error',
            'Course_Teacher`s TeacherId isn`t right'
        };
        Id teacherId = [SELECT Id FROM Teacher__c LIMIT 1].Id;
        Set<Id> coursesId = new Map<Id,Course__c>([SELECT Id FROM Course__c]).keySet();
        
        Test.startTest();
        List<Database.UpsertResult> testResults = UniversityServices.bindTeacherToCourse(teacherId,coursesId);
        Test.stopTest();
        Set<Id> courseTeachersId = new Set<Id>();
        for(Database.UpsertResult testResult : testResults){
            system.assert(testResult.isSuccess(),error[0]);
            courseTeachersId.add(testResult.getId());
        }
        for(Course_Teacher__c courseTeacher : [SELECT Teacher__c FROM Course_Teacher__c]){
            system.assertEquals(teacherId ,courseTeacher.Teacher__c, error[1]);
        }
    }
}