University_system/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>40</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

University_system/force-app/main/default/objects/Course__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>40</relationshipLabel>
    <relationshipName>X40</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/Course_Student__c.object-meta.xml
<CustomObject>
    <label>Course_Student</label>
    <nameField>
        <label>Course_Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course_Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course_Student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Flow__c/fields/Number_of_students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_students__c</fullName>
    <label>Number of students</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Format_of_education__c.field-meta.xml
<CustomField>
    <fullName>Format_of_education__c</fullName>
    <label>Format of education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full time</fullName>
                <default>true</default>
                <label>Full time</label>
            </value>
            <value>
                <fullName>Distance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/classes/CourseStudentTriggerTest.cls
@isTest
public with sharing class CourseStudentTriggerTest {
    @TestSetup
    static void makeData(){
        Specialty__c testSpecialty = new Specialty__c(
            Name = 'TestSpecialty',
            Code__c = 'SP');
        insert testSpecialty;
        Flow__c testFlow = new Flow__c(
            Name = 'flowTest',
            Format_of_education__c = 'FullTime',
            Number_of_students__c = 0,
            Specialty__c = testSpecialty.Id,
            Start_Date__c = Date.today());
        List<Course__c> testCourses = TestDataFactory.generateCourse(testSpecialty.Id, 200);
        insert testFlow;

    }
    @isTest
    static void setCourseStudentNameTest(){
        String error = 'Name of the Course_Student__c record is not right';
        Flow__c testFlow = [SELECT Id, Specialty__c 
                            FROM Flow__c 
                            LIMIT 1];
                  
        Test.startTest();
        insert (TestDataFactory.generateStudents(testFlow.Id, testFlow.Specialty__c,200));
        Test.stopTest();
        List<Course_Student__c> testCourses = [SELECT Name, Course__r.Name, Student__r.Full_Name__c 
                                       FROM Course_Student__c];
        for(Course_Student__c testCourse : testCourses){
            system.assertEquals(testCourse.Student__r.Full_Name__c + '_'+testCourse.Course__r.Name, testCourse.Name, error);
        }                              

    }
}