University_system/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>40</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

University_system/force-app/main/default/objects/Course__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>40</relationshipLabel>
    <relationshipName>X40</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/Course_Student__c.object-meta.xml
<CustomObject>
    <label>Course_Student</label>
    <nameField>
        <label>Course_Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course_Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Course_Student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Course_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Course_Student</relationshipLabel>
    <relationshipName>Course_Student</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Flow__c/fields/Number_of_students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_students__c</fullName>
    <label>Number of students</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/classes/StudentTriggerHandler.cls
public with sharing class StudentTriggerHandler {
    //constructor
    public StudentTriggerHandler() {

    }
    //change number of students in flows, that students assigned
    public void changeNumberOfStudentsInFlow(Student__c[] students){
        Set<Id> flowsId = new Set<Id>();
        for(Student__c student : students){
            flowsId.add(student.Flow__c);
        }
        Map<Id,Flow__c> studentsPerFlow = new Map<Id,Flow__c>([SELECT Id, Number_of_students__c FROM Flow__c WHERE Id in:flowsId]);
        for(Student__c student : students){
            studentsPerFlow.get(student.Flow__c).Number_of_students__c += 1;
        }
        update studentsPerFlow.values();
        return;
    }
    //assign courses to student based on student`s specialty
    public void addStudentToCourses(Student__c[] students){
        Set<Id> specialtyId = new Set<Id>();
        List<Course_Student__c> studentsCourses = new List<Course_Student__c>();
        
        for(Course__c course : [SELECT Specialty__c, Id, Name, Code__c 
                                FROM Course__c ])
        {

            for(Student__c student : students){
                if(student.Specialty__c == course.Specialty__c){
                    studentsCourses.add(new Course_Student__c(Name = student.Name + '_'+ course.Code__c,
                                                                   Student__c = student.Id,
                                                                   Course__c = course.Id));
                    
                }
            }
        }
        
        system.debug(Database.insert(studentsCourses, false));
        
    }
}