University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Format_of_education__c.field-meta.xml
<CustomField>
    <fullName>Format_of_education__c</fullName>
    <label>Format of education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full time</fullName>
                <default>true</default>
                <label>Full time</label>
            </value>
            <value>
                <fullName>Distance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/classes/AddStudentsToFlowTest.cls
@isTest
public with sharing class AddStudentsToFlowTest {
    @TestSetup
    static void makeData(){
        Specialty__c testSpecialty = new Specialty__c(Name='TestSpecialty', Code__c = 'Test');
        insert (testSpecialty);
        insert (new Flow__c(Start_Date__c = Date.today(), Specialty__c = testSpecialty.Id,Format_of_education__c='FullTime'));
    }
    @isTest
    static void addOneStudentToFlow(){
        Flow__c testFlow = 
                [SELECT Id, Specialty__c
                FROM Flow__c 
                LIMIT 1];
        List<StudentDTO> testStudentsDTO = TestDataFactory.generateStudentDTO(1);
        Test.startTest();
        List<Database.SaveResult> results = UniversityServices.addStudentsToFlow(testStudentsDTO,testFlow.Id);
        Test.stopTest();
        List<Student__c> testStudents = [SELECT Flow__c, Specialty__c FROM Student__c];
        for(Student__c testStud : testStudents){
            system.debug('Student`s flow: '+ testStud.Flow__c +  'Specialty: ' +testStud.Specialty__c);
            system.assertEquals(testStud.Flow__c, testFlow.Id);
            system.assertEquals(testStud.Specialty__c, testFlow.Specialty__c);
        }
    }
    @isTest 
    static void addBulkStudentToFlow(){
        Flow__c testFlow = 
                [SELECT Id, Specialty__c
                FROM Flow__c 
                LIMIT 1];
        List<StudentDTO> testStudentsDTO = TestDataFactory.generateStudentDTO(200);
        Test.startTest();
        List<Database.SaveResult> results = UniversityServices.addStudentsToFlow(testStudentsDTO,testFlow.Id);
        Test.stopTest();
        List<Student__c> testStudents = [SELECT Flow__c, Specialty__c FROM Student__c];
        for(Student__c testStud : testStudents){
            system.debug('Student`s flow: '+ testStud.Flow__c +  'Specialty: ' +testStud.Specialty__c);
            system.assertEquals(testStud.Flow__c, testFlow.Id);
            system.assertEquals(testStud.Specialty__c, testFlow.Specialty__c);
        }
    }
}