University_system/force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <label>Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

University_system/force-app/main/default/objects/Student__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <referenceTo>Flow__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Format_of_education__c.field-meta.xml
<CustomField>
    <fullName>Format_of_education__c</fullName>
    <label>Format of education</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full time</fullName>
                <default>true</default>
                <label>Full time</label>
            </value>
            <value>
                <fullName>Distance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Grand__c.field-meta.xml
<CustomField>
    <fullName>Grand__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do you student study for money or by grand</description>
    <label>Grand</label>
    <type>Checkbox</type>
</CustomField>

University_system/force-app/main/default/objects/Student__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <referenceTo>Specialty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

University_system/force-app/main/default/classes/UniversityServices.cls
public with sharing class UniversityServices {
    //create flow
    public static Database.SaveResult createFlow(Id specialtyId, Date startDate, String formatOfEd, String flowName){
        return Database.insert(
            new Flow__c(
                Name = flowName,
                Specialty__c = specialtyId,
                Start_Date__c = startDate,
                Format_of_education__c = formatOfEd  
            ));
    }
    //create student and bind to flow
    public static List<Database.SaveResult> addStudentsToFlow(List<StudentDTO> studsDTO, Id flowId){
        Flow__c flow = [SELECT Specialty__c FROM Flow__c WHERE Id =:flowId];
        List<Student__c> students = new List<Student__c>();
        for(StudentDTO stud : studsDTO){
            students.add(new Student__c(Flow__c = flowId, 
                                        Full_Name__c = stud.fullName, 
                                        Contact_Phone_Number__c = stud.phoneNumber,
                                        Email__c = stud.email,
                                        Grand__c = stud.grand,
                                        Specialty__c = flow.Specialty__c));
        }
        return Database.insert(students, false);
    }
    //bind existed students to flow
    @future
    public static void bindStudentsToFlow(Id flowId, Set<Id> studentsId){
        List<Student__c> studentsToBind = [SELECT Flow__c, Specialty__c FROM Student__c WHERE Id in: studentsId];
        Flow__c flowToBind = [SELECT Specialty__c FROM Flow__c WHERE Id=:flowId LIMIT 1];
        for(Student__c stud : studentsToBind){
            stud.Flow__c = flowId;
            stud.Specialty__c = flowToBind.Specialty__c;
        }
        return;
    }
        
}